admin:
  access_log_path: /var/log/envoy/envoy.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 5454
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /var/log/envoy/envoy.log
              log_format:
                text_format: |
                  [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%"
                  %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION%
                  %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%"
                  "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" "%UPSTREAM_TRANSPORT_FAILURE_REASON%"\n
          # http_filters:
          # - name: envoy.filters.http.header_to_metadata
          #   typed_config:
          #     "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
          #     request_rules:
          #     - header: x-version
          #       on_header_present:
          #         metadata_namespace: envoy.lb
          #         key: version
          #         type: STRING
          #       on_header_missing:
          #         metadata_namespace: envoy.lb
          #         key: default
          #         value: "true"
          #         type: STRING
          #       remove: false
          # - name: envoy.filters.http.router
          #   typed_config:
          #     "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          http_filters:
          - name: envoy.filters.http.router
          - name: envoy.filters.http.header_to_metadata
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
              request_rules:
              - header: x-custom-header
                on_header_present:
                  metadata_namespace: custom
                  key: custom_header
                  type: STRING
              response_rules:
              - header: x-custom-header
                on_header_present:
                  metadata_namespace: custom
                  key: custom_header
                  type: STRING

          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: web_series

  clusters:
  - name: web1_series
    type: LOGICAL_DNS
    connect_timeout: 3s
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: web1_series
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 5000
  - name: web2_series
    type: LOGICAL_DNS
    connect_timeout: 3s
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: web2_series
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 4000


    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          #        sni: www.envoyproxy.io
